### ISSUE TITLE
Quesiton about recent docker/kubernetes developments from docker con. 

### ISSUE THREAD

**Issue by qubusp** [tomkukral/kubernetes-examples#2]
Hi, from the last docker con it came out that now we can use compose-files as manifests for kubernetes. Does this mean, that the trend of docker dying is moved somewhere to a further date? Also - does the compose act as a service or as a pod?

**Comment by tomkukral** [comment]
I don't know why should we lock ourself in `docker-compose` format ... I prefer to use native Kubernetes resources/tooling and don't need any help from Docker.
